
import jsPDF from 'jspdf';
import { Assessment } from '../types';
import { 
  getBMIClassification, 
  getHandgripClassification, 
  getTUGClassification, 
  getSitToStandClassification,
  getKatzClassification,
  getLawtonClassification,
  getTwoMinStepClassification
} from './calculations';

// Helper to load image
const loadImage = (src: string): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.src = src;
        img.onload = () => resolve(img);
        img.onerror = (err) => reject(err);
    });
};

export const generatePDF = async (data: Assessment) => {
  const doc = new jsPDF();
  
  // Colors
  const primaryColor = [30, 64, 175]; // Brand Blue
  const secondaryColor = [101, 163, 13]; // Brand Green
  
  // --- Header ---
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 35, 'F'); // Increased height for logo
  
  // Try to add logo
  try {
      const img = await loadImage('./logo.png');
      // White circle background for logo
      doc.setFillColor(255, 255, 255);
      doc.circle(25, 17, 12, 'F');
      doc.addImage(img, 'PNG', 15, 7, 20, 20);
  } catch (e) {
      console.warn("Logo load failed", e);
  }

  // Header Text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text("SENHORAS & SENHORES", 105, 18, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text("AVALIAÇÃO FÍSICO-FUNCIONAL E GERIÁTRICA", 105, 26, { align: 'center' });

  let y = 50;
  const leftMargin = 14;
  const rightMargin = 196;
  const pageHeight = doc.internal.pageSize.height;
  
  // Helper functions
  const resetText = () => {
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
  };

  const checkPageBreak = (spaceNeeded: number = 15) => {
    if (y + spaceNeeded > 280) {
        doc.addPage();
        y = 20;
        return true;
    }
    return false;
  };

  const addSectionTitle = (title: string) => {
    checkPageBreak(20);
    y += 5;
    // Background strip
    doc.setFillColor(240, 245, 255);
    doc.rect(leftMargin, y - 4, 182, 8, 'F');
    // Accent line
    doc.setDrawColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.setLineWidth(1);
    doc.line(leftMargin, y + 4, leftMargin + 182, y + 4);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(title, leftMargin + 2, y + 1);
    
    y += 12;
    resetText();
  };

  const addRow = (label: string, value: string, info: string = "") => {
    checkPageBreak(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${label}:`, leftMargin + 2, y);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text(value, 90, y);

    if(info) {
        doc.setFontSize(9);
        const infoLower = info.toLowerCase();
        
        // Logic: Green for Positive, Red for Negative, Yellow/Grey for Warning/Intermediate
        // Checks for key words generated by calculations.ts
        
        if (
            infoLower.includes('eutrófico') || 
            infoLower.includes('bom') || 
            infoLower.includes('preservada') || 
            infoLower.includes('independente') || 
            infoLower.includes('independência') ||
            infoLower.includes('normal') ||
            infoLower.includes('dentro/acima')
        ) {
            doc.setTextColor(22, 163, 74); // Green (Success)
        } 
        else if (
            infoLower.includes('atenção') || 
            infoLower.includes('sobrepeso') ||
            infoLower.includes('parcial') ||
            infoLower.includes('leve')
        ) {
            doc.setTextColor(202, 138, 4); // Yellow/Dark Gold (Warning/Intermediate)
        } 
        else if (
            infoLower.includes('risco') || 
            infoLower.includes('dependência') || 
            infoLower.includes('fraco') || 
            infoLower.includes('ruim') ||
            infoLower.includes('baixo peso') ||
            infoLower.includes('abaixo')
        ) {
            doc.setTextColor(220, 38, 38); // Red (Error)
        } else {
            doc.setTextColor(100, 100, 100); // Gray (Neutral)
        }

        doc.text(`(${info})`, 140, y);
        resetText();
    }

    // Light grid line
    doc.setDrawColor(230, 230, 230);
    doc.setLineWidth(0.1);
    doc.line(leftMargin, y + 2, rightMargin, y + 2);
    
    y += 8;
  };

  // --- Content ---

  // 1. Dados Pessoais
  addSectionTitle("DADOS PESSOAIS E SINAIS VITAIS");
  addRow("Nome", data.name);
  addRow("Data de Nascimento", `${data.birthDate.split('-').reverse().join('/')} (${data.calculatedAge} anos)`);
  addRow("Gênero", data.gender === 'male' ? 'Masculino' : 'Feminino');
  addRow("Pressão Arterial (Início)", data.bloodPressureStart || '-');
  addRow("Data da Avaliação", data.assessmentDate.split('-').reverse().join('/'));

  // 2. Antropometria
  addSectionTitle("ANTROPOMETRIA");
  addRow("Estatura", `${data.height} cm`);
  addRow("Massa Corporal", `${data.weight} kg`);
  addRow("IMC", `${data.bmi.toFixed(2)} kg/m²`, getBMIClassification(data.bmi).label);
  addRow("% Gordura", `${data.bodyFatPercentage} %`);
  addRow("% Massa Magra", `${data.leanMassPercentage} %`);

  // 3. Força e Funcionalidade
  addSectionTitle("TESTES DE FORÇA E FUNCIONALIDADE");
  
  const bestSitToStand = Math.min(data.lowerLimbTest1 || 99, data.lowerLimbTest2 || 99);
  const sitStatus = bestSitToStand !== 99 ? getSitToStandClassification(bestSitToStand).label : "";
  addRow("Sit-to-Stand (Melhor Tempo)", bestSitToStand !== 99 ? `${bestSitToStand} s` : "-", sitStatus);
  
  const maxHandgripRight = Math.max(data.handgripRight1, data.handgripRight2);
  const maxHandgripLeft = Math.max(data.handgripLeft1, data.handgripLeft2);
  const handStatusR = getHandgripClassification(data.gender, maxHandgripRight).label;
  const handStatusL = getHandgripClassification(data.gender, maxHandgripLeft).label;

  addRow("Preensão Palmar (Direita)", `${maxHandgripRight} kg`, handStatusR);
  addRow("Preensão Palmar (Esquerda)", `${maxHandgripLeft} kg`, handStatusL);
  
  const tugStatus = getTUGClassification(data.tugTime).label;
  addRow("TUG (Timed Up and Go)", `${data.tugTime} s`, tugStatus);
  
  // 2 Min Step Test
  const stepStatus = getTwoMinStepClassification(data.calculatedAge, data.gender, data.twoMinStepScore).label;
  addRow("Marcha Estacionária (2 min)", `${data.twoMinStepScore} repetições`, stepStatus);

  // 4. Escalas
  addSectionTitle("ESCALAS DE INDEPENDÊNCIA");
  addRow("Escala KATZ (AVD)", `${data.katzScore} / 6`, getKatzClassification(data.katzScore).label);
  addRow("Escala Lawton (AIVD)", `${data.lawtonScore} / 27`, getLawtonClassification(data.lawtonScore).label);

  // 5. Observações
  addSectionTitle("PARECER PROFISSIONAL");
  addRow("Pressão Arterial (Final)", data.bloodPressureEnd || '-');
  
  if (data.notes) {
    y += 5;
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    
    // Use a slightly smaller width to account for padding inside the box
    const splitNotes = doc.splitTextToSize(data.notes, 174); 
    const lineHeight = 5;
    const padding = 4;

    let currentLine = 0;

    while (currentLine < splitNotes.length) {
        const availableSpace = 280 - y;
        // Calculate how many lines fit in the remaining space
        // We subtract padding*2 to account for top and bottom box padding
        const maxLinesOnPage = Math.floor((availableSpace - (padding * 2)) / lineHeight);

        // If not enough space for even one line + padding, new page immediately
        if (maxLinesOnPage <= 0) {
            doc.addPage();
            y = 20;
            continue;
        }

        // Determine lines for this chunk
        const linesToPrint = Math.min(splitNotes.length - currentLine, maxLinesOnPage);
        const boxHeight = (linesToPrint * lineHeight) + (padding * 2);

        // Draw Box
        doc.setDrawColor(180, 180, 180); // Gray border
        doc.setFillColor(252, 252, 252); // Very light gray fill
        doc.roundedRect(leftMargin, y, 182, boxHeight, 2, 2, 'FD');

        // Print Text inside box
        doc.setTextColor(50, 50, 50);
        for (let i = 0; i < linesToPrint; i++) {
            // Text Y position: y + padding + lineOffset + approx baseline correction (4)
            doc.text(splitNotes[currentLine + i], leftMargin + 4, y + padding + (i * lineHeight) + 4);
        }

        // Update cursor
        y += boxHeight + 5;
        currentLine += linesToPrint;

        // If there are still lines left, we need a new page
        if (currentLine < splitNotes.length) {
            doc.addPage();
            y = 20;
        }
    }
  }

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Senhoras & Senhores - Gerado em ${new Date().toLocaleDateString()} - Pág ${i}/${totalPages}`, 105, pageHeight - 10, { align: 'center' });
  }

  doc.save(`Relatorio_${data.name.replace(/\s+/g, '_')}_${data.assessmentDate}.pdf`);
};
